// <auto-generated />
using System;
using Fakebook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fakebook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128154525_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fakebook.Models.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("fakebook_posts");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("PostId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostId");

                    b.ToTable("fakebook_post_comments");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.PostMedia", b =>
                {
                    b.Property<Guid>("PostMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("post_media_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content_type");

                    b.Property<int>("FileType")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("path");

                    b.Property<Guid>("PostId")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_id");

                    b.Property<double>("Size")
                        .HasColumnType("double")
                        .HasColumnName("size");

                    b.HasKey("PostMediaId");

                    b.HasIndex("PostId");

                    b.ToTable("fakebook_post_media");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("profile_id");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId");

                    b.ToTable("fakebook_profiles");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReactedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("reacted_by");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int")
                        .HasColumnName("reaction_type");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("int")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId");

                    b.HasIndex("ReactedBy", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("fakebook_reactions");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.Post", b =>
                {
                    b.HasOne("Fakebook.Models.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.PostComment", b =>
                {
                    b.HasOne("Fakebook.Models.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fakebook.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.PostMedia", b =>
                {
                    b.HasOne("Fakebook.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Fakebook.Models.Entities.Reaction", b =>
                {
                    b.HasOne("Fakebook.Models.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ReactedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
